CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    challenge_id INTEGER NOT NULL,
    height INTEGER DEFAULT 600,
    width INTEGER DEFAULT 800,
    last_modified DATETIME DEFAULT CURRENT_TIMESTAMP
)